version: '3'
services:
    warehousems:
        image: warehousems:latest
        build:
            context: .
            dockerfile: application/backend/Dockerfile
        ports:
            - "8080:8080"
    wms:
        container_name: wms_c
        image: wms_c:latest
        build: 
            context: ./application/frontend/wms
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./application/frontend/wms:/wms